### ISSUE TITLE
integrate speedtest (functionality) as a command

### ISSUE THREAD

**Issue by DKorosec** [DKorosec/windows-terminal-commander#4]

**Comment by tehnuty** [comment]
Can you assign that to me?

**Comment by DKorosec** [comment]
@tehnuty 
Let's implement it that way:
it will run for ~10 seconds and will print out each second the current results of upload / download speed
(example)
running download tests... 
1. 10 MB/s
2. 55 MB/s
.
.
5. 112 MB/s



running upload tests..

1. 1.5 MB/s
2. 5 MB/s
.
.
5. 12 MB/s


and lets say we also add average to final result?

**Comment by DKorosec** [comment]
Implemented :)
